name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Go to android dir and build
      run: |
        cd /home/runner/work/sudachi/sudachi/src/android
        chmod +x gradlew
        ./gradlew build
      
    - uses: actions/upload-artifact@v4
      with:
        name: Sudachi-emu
        path: /bin
