name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 17
        distribution: microsoft
        cache: gradle
    
    - name: clone repo
      run: |
        mkdir -p /home/runner/work/tmp
        cd /home/runner/work/tmp
        git clone --recursive https://github.com/sudachi-emu/sudachi.git
    
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: 1.3.280.0
        cache: true
        
    - name: Go to android dir and build
      run: |
        pwd
        cd /home/runner/work/tmp/sudachi/src/android
        chmod a+x gradlew
        ./gradlew build
      
    - uses: actions/upload-artifact@v4
      with:
        name: Sudachi-emu
        path: /home/runner/work/tmp/sudachi/bin/*
